######################################################################
# Automatically generated by qmake (3.0) Tue Aug 25 14:44:33 2015
######################################################################

TEMPLATE = app
TARGET = emoxone_webrtc_bridge
INCLUDEPATH += .
QT += network

# Input
HEADERS += Webrtc.h ImageListener.h
SOURCES += main.cpp ImageListener.cpp

LIBS += -L/usr/lib/OpenNI2/Drivers -lOpenNI2 -lDummyDevice -lOniFile -lPS1080

